server:
  port: 8082
spring:
  thymeleaf:
    cache: false  # \u5173\u95ED\u7F13\u5B58\uFF0C\u52A8\u6001\u66F4\u65B0
    mode: LEGACYHTML5

  #\u914D\u7F6E\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
  dubbo:
    application:
      name: gmall-manage-web
    registry:
      protocol: zookeeper
      address: dsjrz8:2181
    base-package: com.atguigu.gmall
    protocol:
      name: dubbo
    consumer:
      timeout: 10000
      check: false  # \u5173\u95ED\u68C0\u67E5\uFF0C\u8FD9\u6837\u5C31\u5373\u4F7F\u5F53\u6CE8\u518C\u4E2D\u5FC3\u6CA1\u6709\u5F00\u542F\uFF0C\u90A3\u4E48\u53EA\u8981\u4E0D\u9700\u8981\u53D1\u73B0\u6CE8\u518C\u4E2D\u5FC3\u7684\u670D\u52A1\uFF0C\u90A3\u4E48\u5C31\u4E0D\u4F1A\u62A5\u9519

# 自定义配置: fastdfs文件服务器
fileServer:
    url: http://dsjrz8