spring:
  datasource:
    url: jdbc:mysql://dsjrz8:3306/gmall?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: python123
  dubbo:
    application:
      name: gmall-user-manage
    registry:
      protocol: zookeeper
      address: dsjrz8:2181
    base-package: com.atguigu.gmall
    protocol:
      name: dubbo
  redis:
    host: dsjrz8
    port: 6379
    database: 0

#server:
#  port: 8090


#spring.redis.host=192.168.67.201