spring:
  datasource:
    url: jdbc:mysql://dsjrz8:3306/gmall?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: python123
  dubbo:
    application:
      name: gmall-user-manage
    registry:
      protocol: zookeeper
      address: dsjrz8:2181
    base-package: com.atguigu.gmall
    protocol:
      name: dubbo

server:
  port: 8090


# \u914D\u7F6E\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740